### ISSUE TITLE
error: cannot convert 'const __FlashStringHelper*' to 'char*' for argument '1' to ..- SOLVED (sort of)

### ISSUE THREAD

**Issue by k2OS** [mpflaga/Arduino-MemoryFree#2]
See edit below.

I love this little library. It helped me out greatly when I made a "reverse geoache" for my sisters wedding a few years ago :)

Now, several years later, I've updated my arduino IDE and libraries and now I can't compile my code with this library.

In every place where I output something to my LCD through a wrapper-function (to write the text onto the LCD one character at a time), I now get this error:

error: cannot convert 'const __FlashStringHelper*' to 'char*' for argument '1' to 'void stringToLCD(char*)'

I call it like this: 
stringToLCD(F("Example text")); 

It worked flawlessly with the older version of the libray and Arduino IDE 1.0.3 (no idea what version the library is.. the way to use the old version was with  getPSTR("some text").
This works like a charm inside Serial.print(), lcd.print, but not my own function.

My own function is constructed like this: (read: I found it on the internet)

void stringToLCD(char *stringIn) {
    int lineCount = 0;
    int lineNumber = 0;
    byte stillProcessing = 1;
    byte charCount = 1;
    lcd.clear();
    lcd.setCursor(0,0);

    while(stillProcessing) {
         if (++lineCount > 20) {    // have we printed 20 characters yet (+1 for the logic)
              lineNumber += 1;
              lcd.setCursor(0,lineNumber);   // move cursor down
              lineCount = 1;
         }

         lcd.print((stringIn[charCount - 1]);

         if (!stringIn[charCount]) {   // no more chars to process?
              stillProcessing = 0;
         }
         charCount += 1;
          delay(100);
    }
}

It's probably something very silly and most likely something in the Arduino IDE that has changed from 1.0.3 to 1.6.5, but I thought I'd give it a go here first.. 

Cheers!

/rené

EDIT: I later found this guide: http://deans-avr-tutorials.googlecode.com/svn/trunk/Progmem/Output/Progmem.pdf

Using the function PSTR() that is exposed in avr/pgmspace.h did exactly what I needed, so sadly this library is out for me.

**Comment by mpflaga** [comment]
from 1.0.x to 1.5 the gcc compiler was updated and it is significantly more strict. Hence the errors. Where pgmStrToRAM.h has some problems with the newer compiler. Your above snippet of code does not appear to have any use of either pgmStrToRAM or MemoryFree.

I do see that your snippet has the __FlashStringHelper error. This is because the output of the F() function is a (char const *) and your definition it is a (char *). Hence the miss-match.

I was able to compile it with the following change, brute forcing the cast.

    stringToLCD((char *) F("Example text"));

**Comment by k2OS** [comment]
I did use pgmStrToRam... not in the StringToLCD function, but I called it like this: 

stringToLCD(F("Example text"));

I am guessing this was enough (and I need to add the forced cast).

Is there any difference between using this library and F() vs. PSTR() from avr/pgmspace.h?

Thank you for the reply :)

**Comment by k2OS** [comment]
By accident, I came by here again as a friend of mine was having memory issues as well.. and I noticed that the pgmToRAM.h and .cpp-files had been updated 13 days ago.. now my GPS-box-sketch compiles in 1.6.5 again, with _no_ modificatins \o/.

I can see from my previous posts that I muddled things.. I was and am using 'getPSTR("some text") to put things into RAM - that didn't work for a while. but does so again nicely - even things I want to print to LCD, so I am as happy as can be :)
