### ISSUE TITLE
another free memory calculation method

### ISSUE THREAD

**Issue by soundanalogous** [mpflaga/Arduino-MemoryFree#6]
This is another way that seems to work across various Arduino architectures. I've used it with Teensy and with SAMD boards (Arduino Zero) and with the Arduino 101 (can't remember if I tried this with AVR as well). I'm not sure how reliable this is however.

```c++
uint32_t FreeRam() {
    uint32_t stackTop;
    uint32_t heapTop;

    // current position of the stack.
    stackTop = (uint32_t) &stackTop;

    // current position of heap.
    void* hTop = malloc(1);
    heapTop = (uint32_t) hTop;
    free(hTop);

    // The difference is the free, available ram.
    return stackTop - heapTop;
}
```

I found the above snippet here: https://forum.pjrc.com/threads/23256-Get-Free-Memory-for-Teensy-3-0?p=34242&viewfull=1#post34242.

**Comment by mpflaga** [comment]
interesting, seams to make sense. have not tried it on AVR either. At the moment since the existing methods appears to work and is tested. I shall defer this to when or if needed for this fork. But will keep it in mind.
